config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'about' => 'top#about', as: :about
  get 'hello(/:name)' => 'hello#show', as: :hello
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def show
    @name = params[:name]|| 'world'
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hello/show.html.erb
<%
  @document_title = "SimpleGreeter (#{@name})"
%>
<div class="card m-3">
  <%= image_tag 'robot.svg', alt: 'Robot',
    style: 'margin: auto; width: 100%; max-width: 320px' %>
  <div class="card-body bg-success text-white">
    <p class="card-text lead">
      <i class="fa fa-smile-o"></i>
      Hello, <%= @name %>!
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= @document_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('simple_greeter.ico') %>
    <%= favicon_link_tag('robot256.png', rel: 'apple-touch-icon') %>
  </head>

  <body>
    <header>
      <h1><%= link_to 'SimpleGreeter', :root %></h1>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      &copy; 2016 Oiax Inc.
    </footer>
  </body>
</html>

app/views/top/about.html.erb
<%
  @document_title = "SimpleGreeter - このサイトについて"
%>
<h1>このサイトについて</h1>
<p>SimpleGreeterは『Ruby on Rails 5.0 初級①』の学習用Railsアプリです。</p>

app/views/top/index.html.erb
<%
  @document_title = "SimpleGreeter"
  names = %w(Alice Bob Charlie)
%>
<div class="jumbotron m-3">
  <h1 class="display-3">SimpleGreeter</h1>
  <p class="lead">SimpleGreeterへようこそ！</p>
  <hr>
  <p><%= link_to 'このサイトについて', :about %></p>
</div>
<nav class="nav nav-inline mb-3 justify-content-center">
  <% names.each do |name| %>
    <%= link_to name, hello_path(name: name), class: 'nav-link' %>
  <% end %>
</nav>